#!/bin/bash
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${SCRIPTDIR}"

VERSION="1.3"
DISTDIR="${SCRIPTDIR}/dist-${VERSION}"
DISTSRCDIR="${DISTDIR}/cfsticker-${VERSION}"
DISTZIPFILE="cfsticker-${VERSION}.zip"

./clean
./build
rm -rf ${DISTDIR}
mkdir -p ${DISTDIR}
mkdir -p ${DISTSRCDIR}

if [ -d target ]
then
  cd target
  cp -r readme.txt license.txt cfsticker cfsticker-${VERSION}.jar cfsticker.json lib ${DISTSRCDIR}
  cd ${DISTSRCDIR}
  chmod +x cfsticker
  cd ${DISTDIR}
  zip -r ${DISTZIPFILE} cfsticker-${VERSION}
  cd ${SCRIPTDIR}
fi

